<h2>Securing Your BookYourBeds Password</h2>

<p>Hi <?php echo $user_firstname; ?>,</p>

<p>At <strong>BookYourBeds</strong> we take the security of your account and that of your customer's details very seriously. We are constantly working to improve the reliability of our system and to give you and your customers the best experience possible.</p>

<p>We have just implemented a new system to make your account even more secure, and as part of this we had to reset your password. We never store your password in a 'readable' format, so when we implemented our new encryption system we were unable to transfer your existing password across.</p>

<p>Your new temporary password is:<br /><br />

<code><strong><?php echo $password; ?></strong></code><br /><br />

Please note: all letters as case-sensitive.  Please take the time to reset it to something more memorable (using our new and improved encryption) by <?php echo anchor('signin', 'logging in'); ?> and going to the <em>Settings > Personal Settings</em> menu. Please note that this new password has been randomly generated by our system and sent directly to you - we have kept no readable record of it.</p>

<p>If you have any questions regarding this update to the <strong>BookYourBeds</strong> system please do not hesitate to contact us at <?php echo mailto('mail@bookyourbeds.com'); ?>.</p>

<p>Thanks!</p>

<p><strong>The BookYourBeds Team</strong></p>